tag: medmoe_vqa
dataset_path: /mnt/data/haoqiang/workspace/data/omni-med-vqa-mini
dataset_kwargs:
  token: True
task: "omni_med_vqa_mini"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.omni_med_vqa_mini_doc_to_visual
doc_to_text: !function utils.omni_med_vqa_mini_doc_to_text
doc_to_target: "label"
generation_kwargs:
  max_new_tokens: 256
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
# The return value of process_results will be used by metrics
process_results: !function utils.omni_med_vqa_mini_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: accuracy
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: "Medical question with several options; only one is correct. Refer to the image for clues.\n"
    post_prompt: "\nAnalyze the image and select the correct option. Format your response as: 'Answer: (X) - [brief one-sentence justification]'"
metadata:
  - version: 0.0
