dataset_path: simwit/mimic-cxr
dataset_kwargs:
  token: true
task: "mimic_cxr"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.mimic_cxr_doc_to_visual
doc_to_text: !function utils.mimic_cxr_doc_to_text
doc_to_target: "report"
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.mimic_cxr_process_results
metric_list:
  - metric: bleu_4
    aggregation: mean
    higher_is_better: true
  - metric: rouge_l
    aggregation: mean
    higher_is_better: true
  - metric: meteor
    aggregation: mean
    higher_is_better: true
  - metric: ratescore
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nPlease generate a report for the given images, including both findings and impressions. Return the report in the following format: Findings: {} Impression: {}."
metadata:
  version: 1.0
