dataset_path: GBaker/MedQA-USMLE-4-options
dataset_kwargs:
  token: true
task: "medqa_usmle"
test_split: test
output_type: generate_until
doc_to_text: !function utils.medqa_usmle_doc_to_text
doc_to_target: "answer_idx"
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
process_results: !function utils.medqa_usmle_process_results
metric_list:
  - metric: accuracy
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly."
  think:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices and put the letter in one \"\\boxed{}\"."
metadata:
  version: 1.0
